import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { Footer, Header } from "@/app/components";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "SolarEnergy",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/*<meta httpEquiv="x-ua-compatible" content="ie=edge" />*/}
        {/*<meta*/}
        {/*  name="viewport"*/}
        {/*  content="width=device-width, initial-scale=0, maximum-scale=0"*/}
        {/*/>*/}
        {/*<meta name="viewport" content="width=device-width, initial-scale=10" />*/}
        <title>Cabinetul personal al clientului</title>
        {/*<meta*/}
        {/*  name="viewport"*/}
        {/*  content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover"*/}
        {/*/>*/}
      </head>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
